"""tasks

Revision ID: 0002_tasks
Revises: 0001_foundation
Create Date: 2026-07-23 00:44:41.867009
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0002_tasks"
down_revision: str | None = "0001_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("importance", sa.SmallInteger(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("actual_minutes", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("is_fixed", sa.Boolean(), nullable=False),
        sa.Column("is_ai_adjustable", sa.Boolean(), nullable=False),
        sa.Column("is_splittable", sa.Boolean(), nullable=False),
        sa.Column("energy_level", sa.String(length=16), nullable=True),
        sa.Column("recurrence_rule", sa.Text(), nullable=True),
        sa.Column("recurrence_parent_id", sa.UUID(), nullable=True),
        sa.Column("occurrence_date", sa.Date(), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("habit_id", sa.UUID(), nullable=True),
        sa.Column("habit_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('todo','in_progress','completed','cancelled')",
            name=op.f("ck_tasks_task_status"),
        ),
        sa.CheckConstraint(
            "type in ('task','fixed_event','habit_task','reminder','note')",
            name=op.f("ck_tasks_task_type"),
        ),
        sa.CheckConstraint(
            "due_at is null or start_at is null or due_at >= start_at",
            name=op.f("ck_tasks_task_due_after_start"),
        ),
        sa.CheckConstraint(
            "importance >= 0 and importance <= 4", name=op.f("ck_tasks_task_importance")
        ),
        sa.CheckConstraint(
            "not (is_fixed and is_ai_adjustable)",
            name=op.f("ck_tasks_task_fixed_not_ai_adjustable"),
        ),
        sa.CheckConstraint("priority >= 0 and priority <= 4", name=op.f("ck_tasks_task_priority")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_tasks_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_tasks_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("user_id", "habit_id", "habit_date", name="uq_tasks_user_habit_date"),
        sa.UniqueConstraint(
            "user_id",
            "recurrence_parent_id",
            "occurrence_date",
            name="uq_tasks_user_recurrence_occurrence",
        ),
    )
    op.create_index("ix_tasks_user_id_deleted_at", "tasks", ["user_id", "deleted_at"], unique=False)
    op.create_index("ix_tasks_user_id_start_at", "tasks", ["user_id", "start_at"], unique=False)
    op.create_index(
        "ix_tasks_user_id_status_due_at", "tasks", ["user_id", "status", "due_at"], unique=False
    )
    op.create_table(
        "task_tags",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_task_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_tags_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_task_tags_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("task_id", "tag_id", name=op.f("pk_task_tags")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_tags")
    op.drop_index("ix_tasks_user_id_status_due_at", table_name="tasks")
    op.drop_index("ix_tasks_user_id_start_at", table_name="tasks")
    op.drop_index("ix_tasks_user_id_deleted_at", table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
