"""captures

Revision ID: 0006_captures
Revises: 0005_voice_uploads
Create Date: 2026-07-23 10:33:20.036180
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0006_captures"
down_revision: str | None = "0005_voice_uploads"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "captures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("title_user", sa.String(length=240), nullable=True),
        sa.Column("description_user", sa.Text(), nullable=True),
        sa.Column("brand_user", sa.String(length=120), nullable=True),
        sa.Column("model_user", sa.String(length=120), nullable=True),
        sa.Column("material_user", sa.String(length=120), nullable=True),
        sa.Column("color_user", sa.String(length=80), nullable=True),
        sa.Column("storage_location_user", sa.String(length=240), nullable=True),
        sa.Column("title_ai", sa.String(length=240), nullable=True),
        sa.Column("description_ai", sa.Text(), nullable=True),
        sa.Column("brand_ai", sa.String(length=120), nullable=True),
        sa.Column("model_ai", sa.String(length=120), nullable=True),
        sa.Column("material_ai", sa.String(length=120), nullable=True),
        sa.Column("color_ai", sa.String(length=80), nullable=True),
        sa.Column("storage_location_ai", sa.String(length=240), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("category_ai_id", sa.UUID(), nullable=True),
        sa.Column("purchased_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purchase_place", sa.String(length=240), nullable=True),
        sa.Column("purchase_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("usage_status", sa.String(length=24), nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("ai_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("processing_status", sa.String(length=24), nullable=False),
        sa.Column("possible_duplicate_of", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "processing_status in ('pending','processing','ready','needs_input','failed')",
            name=op.f("ck_captures_capture_processing_status"),
        ),
        sa.CheckConstraint(
            "type in ('item','inspiration','note','image','document','link','location','purchase','blog_material')",
            name=op.f("ck_captures_capture_type"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_captures_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_captures_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_captures")),
    )
    op.create_index(
        "ix_captures_user_id_deleted_at", "captures", ["user_id", "deleted_at"], unique=False
    )
    op.create_index("ix_captures_user_id_type", "captures", ["user_id", "type"], unique=False)
    op.create_table(
        "capture_ai_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("capture_id", sa.Uuid(), nullable=False),
        sa.Column("tag_name", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["capture_id"],
            ["captures.id"],
            name=op.f("fk_capture_ai_tags_capture_id_captures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_capture_ai_tags_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capture_ai_tags")),
    )
    op.create_table(
        "capture_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("capture_id", sa.Uuid(), nullable=False),
        sa.Column("upload_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("bucket", sa.String(length=120), nullable=True),
        sa.Column("media_type", sa.String(length=120), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("exif_json_sanitized", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("gps_removed", sa.Boolean(), nullable=False),
        sa.Column("processing_version", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role in ('original','thumbnail','preview','attachment','audio')",
            name=op.f("ck_capture_assets_capture_asset_role"),
        ),
        sa.CheckConstraint(
            "status in ('uploading','ready','failed','deleted')",
            name=op.f("ck_capture_assets_capture_asset_status"),
        ),
        sa.ForeignKeyConstraint(
            ["capture_id"],
            ["captures.id"],
            name=op.f("fk_capture_assets_capture_id_captures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_capture_assets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capture_assets")),
    )
    op.create_index("ix_capture_assets_capture_id", "capture_assets", ["capture_id"], unique=False)
    op.create_index(
        "ix_capture_assets_user_id_sha256", "capture_assets", ["user_id", "sha256"], unique=False
    )
    op.create_table(
        "capture_tags",
        sa.Column("capture_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["capture_id"],
            ["captures.id"],
            name=op.f("fk_capture_tags_capture_id_captures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_capture_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_capture_tags_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("capture_id", "tag_id", name=op.f("pk_capture_tags")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("capture_tags")
    op.drop_index("ix_capture_assets_user_id_sha256", table_name="capture_assets")
    op.drop_index("ix_capture_assets_capture_id", table_name="capture_assets")
    op.drop_table("capture_assets")
    op.drop_table("capture_ai_tags")
    op.drop_index("ix_captures_user_id_type", table_name="captures")
    op.drop_index("ix_captures_user_id_deleted_at", table_name="captures")
    op.drop_table("captures")
    # ### end Alembic commands ###
