"""search

Revision ID: 0007_search
Revises: 0006_captures
Create Date: 2026-07-23 10:48:24.937154
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0007_search"
down_revision: str | None = "0006_captures"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("tags_text", sa.Text(), nullable=True),
        sa.Column("category_text", sa.Text(), nullable=True),
        sa.Column("metadata_text", sa.Text(), nullable=True),
        sa.Column("document_tsv", postgresql.TSVECTOR(), nullable=True),
        sa.Column("thumbnail_asset_id", sa.UUID(), nullable=True),
        sa.Column("entity_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "indexed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_search_documents_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_documents")),
        sa.UniqueConstraint(
            "user_id", "entity_type", "entity_id", name="uq_search_documents_user_entity"
        ),
    )
    op.create_index(
        "ix_search_documents_tsv",
        "search_documents",
        ["document_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_search_documents_user_type",
        "search_documents",
        ["user_id", "entity_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_search_documents_user_type", table_name="search_documents")
    op.drop_index("ix_search_documents_tsv", table_name="search_documents", postgresql_using="gin")
    op.drop_table("search_documents")
    # ### end Alembic commands ###
