"""blog_content_management

Revision ID: 0011_blog_content_management
Revises: 0010_task_note_any_attachment
Create Date: 2026-07-28 21:29:51.471868
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0011_blog_content_management'
down_revision: str | None = '0010_task_note_any_attachment'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('schema_version', sa.String(length=24), nullable=False),
    sa.Column('create_defaults_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clipboard_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('url_capture_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_apply_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('word_cloud_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blog_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_blog_settings'))
    )
    op.create_table('blog_skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blog_skills_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_skills'))
    )
    op.create_index('uq_blog_skill_name', 'blog_skills', ['user_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at is null'))
    op.create_table('post_content_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content_class', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('field_schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_system_seed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_content_types_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_content_types')),
    sa.UniqueConstraint('user_id', 'key', name='uq_content_type_user_key')
    )
    op.create_table('post_keywords',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_text', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_stop_word', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_keywords_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_keywords')),
    sa.UniqueConstraint('user_id', 'canonical_text', name='uq_keyword_user_text')
    )
    op.create_table('post_taxonomy_merges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('affected_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('async_job_id', sa.UUID(), nullable=True),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('category','tag','keyword')", name=op.f('ck_post_taxonomy_merges_taxonomy_merge_kind')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_taxonomy_merges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_taxonomy_merges'))
    )
    op.create_table('post_word_cloud_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_kind', sa.String(length=12), nullable=False),
    sa.Column('filter_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filter_hash', sa.String(length=64), nullable=False),
    sa.Column('terms_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('async_job_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.CheckConstraint("source_kind in ('tag','keyword')", name=op.f('ck_post_word_cloud_snapshots_wordcloud_source_kind')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_word_cloud_snapshots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_word_cloud_snapshots')),
    sa.UniqueConstraint('user_id', 'source_kind', 'filter_hash', name='uq_wordcloud_scope')
    )
    op.create_table('blog_skill_defaults',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('scope_key', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope_type in ('global','content_class','content_type')", name=op.f('ck_blog_skill_defaults_skill_default_scope')),
    sa.ForeignKeyConstraint(['skill_id'], ['blog_skills.id'], name=op.f('fk_blog_skill_defaults_skill_id_blog_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blog_skill_defaults_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_skill_defaults')),
    sa.UniqueConstraint('user_id', 'scope_type', 'scope_key', name='uq_skill_default_scope')
    )
    op.create_table('blog_skill_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('recommended_model', sa.String(length=120), nullable=True),
    sa.Column('max_content_chars', sa.Integer(), nullable=False),
    sa.Column('long_content_strategy', sa.String(length=24), nullable=False),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("long_content_strategy in ('reject','chunk','summarize_then_process')", name=op.f('ck_blog_skill_versions_skill_version_strategy')),
    sa.ForeignKeyConstraint(['skill_id'], ['blog_skills.id'], name=op.f('fk_blog_skill_versions_skill_id_blog_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blog_skill_versions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_skill_versions')),
    sa.UniqueConstraint('skill_id', 'version_number', name='uq_skill_version_number')
    )
    op.create_table('post_ai_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('async_job_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('base_revision_id', sa.UUID(), nullable=False),
    sa.Column('optimization_type', sa.String(length=16), nullable=False),
    sa.Column('content_class', sa.String(length=16), nullable=False),
    sa.Column('content_type_id', sa.UUID(), nullable=True),
    sa.Column('skill_version_id', sa.UUID(), nullable=False),
    sa.Column('model_key', sa.String(length=120), nullable=False),
    sa.Column('ai_schema_version', sa.String(length=32), nullable=False),
    sa.Column('field_policy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('protected_tokens_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.String(length=12), nullable=True),
    sa.Column('validation_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_ai_runs_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_ai_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_ai_runs')),
    sa.UniqueConstraint('async_job_id', name='uq_ai_run_job')
    )
    op.create_index('ix_ai_runs_user_post', 'post_ai_runs', ['user_id', 'post_id', 'created_at'], unique=False)
    op.create_table('post_category_profiles',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_post_category_profiles_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_category_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_post_category_profiles'))
    )
    op.create_table('post_keyword_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['post_keywords.id'], name=op.f('fk_post_keyword_aliases_keyword_id_post_keywords'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_keyword_aliases_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_keyword_aliases')),
    sa.UniqueConstraint('user_id', 'alias', name='uq_keyword_alias_user_alias')
    )
    op.create_table('post_keyword_links',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source in ('user','ai','recomputed','import')", name=op.f('ck_post_keyword_links_keyword_link_source')),
    sa.ForeignKeyConstraint(['keyword_id'], ['post_keywords.id'], name=op.f('fk_post_keyword_links_keyword_id_post_keywords'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_keyword_links_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_keyword_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'keyword_id', name=op.f('pk_post_keyword_links'))
    )
    op.create_table('post_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('detected_format', sa.String(length=12), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('source_site', sa.String(length=240), nullable=True),
    sa.Column('source_author', sa.String(length=240), nullable=True),
    sa.Column('source_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_title', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('normalized_markdown', sa.Text(), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_object_key', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('fetch_attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('async_job_id', sa.UUID(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type <> 'url' or original_url is not null", name=op.f('ck_post_sources_post_source_url_required')),
    sa.CheckConstraint("source_type in ('blank','clipboard','url','quick','template','file')", name=op.f('ck_post_sources_post_source_type')),
    sa.CheckConstraint("status in ('saved','pending','processing','partial','completed','failed','cancelled')", name=op.f('ck_post_sources_post_source_status')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_sources_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_sources_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_sources'))
    )
    op.create_index('ix_post_sources_user_post', 'post_sources', ['user_id', 'post_id', 'created_at'], unique=False)
    op.create_index('ix_post_sources_user_status', 'post_sources', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_post_sources_user_url', 'post_sources', ['user_id', 'original_url'], unique=False, postgresql_where=sa.text('original_url is not null'))
    op.create_table('post_tag_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_post_tag_aliases_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_tag_aliases_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_tag_aliases')),
    sa.UniqueConstraint('user_id', 'alias', name='uq_tag_alias_user_alias')
    )
    op.create_table('post_tag_profiles',
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_post_tag_profiles_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_tag_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', name=op.f('pk_post_tag_profiles'))
    )
    op.create_table('post_ai_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('ai_run_id', sa.Uuid(), nullable=False),
    sa.Column('base_revision_id', sa.UUID(), nullable=False),
    sa.Column('candidate_revision_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('field_diff_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applied_revision_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('pending','merge_required','applied','rejected','copied')", name=op.f('ck_post_ai_candidates_candidate_status')),
    sa.ForeignKeyConstraint(['ai_run_id'], ['post_ai_runs.id'], name=op.f('fk_post_ai_candidates_ai_run_id_post_ai_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_ai_candidates_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_ai_candidates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_ai_candidates')),
    sa.UniqueConstraint('ai_run_id', name='uq_candidate_run')
    )
    op.create_table('post_candidate_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('selected_fields_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rejected_fields_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_revision_before_id', sa.UUID(), nullable=False),
    sa.Column('result_revision_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action in ('apply_all','apply_body','apply_metadata','apply_fields','keep_current','reject','copy')", name=op.f('ck_post_candidate_decisions_candidate_decision_action')),
    sa.ForeignKeyConstraint(['candidate_id'], ['post_ai_candidates.id'], name=op.f('fk_post_candidate_decisions_candidate_id_post_ai_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_candidate_decisions_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_candidate_decisions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_candidate_decisions'))
    )
    op.add_column('post_revisions', sa.Column('base_revision_id', sa.UUID(), nullable=True))
    op.add_column('post_revisions', sa.Column('revision_number', sa.Integer(), nullable=True))
    op.add_column('post_revisions', sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.add_column('post_revisions', sa.Column('async_job_id', sa.UUID(), nullable=True))
    op.add_column('post_revisions', sa.Column('skill_version_id', sa.UUID(), nullable=True))
    op.add_column('post_revisions', sa.Column('schema_version', sa.String(length=24), nullable=False, server_default='post-revision.v1'))
    op.alter_column('post_revisions', 'source',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.create_index('uq_post_revisions_number', 'post_revisions', ['post_id', 'revision_number'], unique=True, postgresql_where=sa.text('revision_number IS NOT NULL'))
    op.add_column('posts', sa.Column('subtitle', sa.String(length=240), nullable=True))
    op.add_column('posts', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('content_status', sa.String(length=24), nullable=False, server_default='draft'))
    op.add_column('posts', sa.Column('content_class', sa.String(length=16), nullable=False, server_default='essay'))
    op.add_column('posts', sa.Column('content_type_id', sa.UUID(), nullable=True))
    op.add_column('posts', sa.Column('language', sa.String(length=16), nullable=False, server_default='zh-CN'))
    op.add_column('posts', sa.Column('editor_mode', sa.String(length=10), nullable=False, server_default='markdown'))
    op.add_column('posts', sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('location_text', sa.String(length=240), nullable=True))
    op.add_column('posts', sa.Column('project_text', sa.String(length=240), nullable=True))
    op.add_column('posts', sa.Column('structured_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.add_column('posts', sa.Column('latest_ai_status', sa.String(length=24), nullable=True))
    op.add_column('posts', sa.Column('first_ai_optimized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('last_ai_optimized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('ai_optimization_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('posts', sa.Column('last_skill_version_id', sa.UUID(), nullable=True))
    op.alter_column('post_revisions', 'snapshot_json', server_default=None)
    op.alter_column('post_revisions', 'schema_version', server_default=None)
    op.alter_column('posts', 'content_status', server_default=None)
    op.alter_column('posts', 'content_class', server_default=None)
    op.alter_column('posts', 'language', server_default=None)
    op.alter_column('posts', 'editor_mode', server_default=None)
    op.alter_column('posts', 'structured_data_json', server_default=None)
    op.alter_column('posts', 'ai_optimization_count', server_default=None)
    op.create_index('ix_posts_user_content_class', 'posts', ['user_id', 'content_class', 'content_type_id'], unique=False)
    op.create_index('ix_posts_user_content_status', 'posts', ['user_id', 'content_status', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_user_content_status', table_name='posts')
    op.drop_index('ix_posts_user_content_class', table_name='posts')
    op.drop_column('posts', 'last_skill_version_id')
    op.drop_column('posts', 'ai_optimization_count')
    op.drop_column('posts', 'last_ai_optimized_at')
    op.drop_column('posts', 'first_ai_optimized_at')
    op.drop_column('posts', 'latest_ai_status')
    op.drop_column('posts', 'structured_data_json')
    op.drop_column('posts', 'project_text')
    op.drop_column('posts', 'location_text')
    op.drop_column('posts', 'occurred_at')
    op.drop_column('posts', 'editor_mode')
    op.drop_column('posts', 'language')
    op.drop_column('posts', 'content_type_id')
    op.drop_column('posts', 'content_class')
    op.drop_column('posts', 'content_status')
    op.drop_column('posts', 'summary')
    op.drop_column('posts', 'subtitle')
    op.drop_index('uq_post_revisions_number', table_name='post_revisions', postgresql_where=sa.text('revision_number IS NOT NULL'))
    op.alter_column('post_revisions', 'source',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_column('post_revisions', 'schema_version')
    op.drop_column('post_revisions', 'skill_version_id')
    op.drop_column('post_revisions', 'async_job_id')
    op.drop_column('post_revisions', 'snapshot_json')
    op.drop_column('post_revisions', 'revision_number')
    op.drop_column('post_revisions', 'base_revision_id')
    op.drop_table('post_candidate_decisions')
    op.drop_table('post_ai_candidates')
    op.drop_table('post_tag_profiles')
    op.drop_table('post_tag_aliases')
    op.drop_index('ix_post_sources_user_url', table_name='post_sources', postgresql_where=sa.text('original_url is not null'))
    op.drop_index('ix_post_sources_user_status', table_name='post_sources')
    op.drop_index('ix_post_sources_user_post', table_name='post_sources')
    op.drop_table('post_sources')
    op.drop_table('post_keyword_links')
    op.drop_table('post_keyword_aliases')
    op.drop_table('post_category_profiles')
    op.drop_index('ix_ai_runs_user_post', table_name='post_ai_runs')
    op.drop_table('post_ai_runs')
    op.drop_table('blog_skill_versions')
    op.drop_table('blog_skill_defaults')
    op.drop_table('post_word_cloud_snapshots')
    op.drop_table('post_taxonomy_merges')
    op.drop_table('post_keywords')
    op.drop_table('post_content_types')
    op.drop_index('uq_blog_skill_name', table_name='blog_skills', postgresql_where=sa.text('deleted_at is null'))
    op.drop_table('blog_skills')
    op.drop_table('blog_settings')
    # ### end Alembic commands ###
